Set up unit tests
samsontmr/oss-bot-js pull request #18
Opened 2017-03-06 11:45 UTC by Skaty

2017-03-06 12:13 UTC, li-kai requested changes
Generally looks good!

2017-03-06 12:13 UTC, li-kai commented on .travis.yml
> +  - "5"
Testing on node 6 should be better since node 6 is LTS. More about Node.js release schedule can be found [here](https://github.com/nodejs/LTS).

2017-03-06 12:13 UTC, li-kai commented on package.json
> +  "devDependencies": {
It's convention to have devDependencies right below dependencies

2017-03-06 12:16 UTC, Skaty commented on .travis.yml
> +  - "5"
Hmm, have to check with @samsontmr on what node version he is running the bot on.

2017-03-06 12:16 UTC, Skaty commented on package.json
> +  "devDependencies": {
Alright.

2017-03-06 12:19 UTC, samsontmr commented
@Skaty could you add unit tests for the functions in index.js too? I'll move the tests when I refactor the file.

2017-03-06 12:29 UTC, samsontmr commented on .travis.yml
> +  - "5"
according to package.json, it's currently running 5.9.1. Can change to 6 though, shouldn't be a problem.

2017-03-06 16:49 UTC, Skaty commented
@samsontmr It's harder to test `index.js` at this moment, as the actual GitHub logic is not separated. Do you want me to do it?

2017-03-07 00:07 UTC, samsontmr commented
@skaty just create tests for those methods that don't involve calling the github api then, especially buildResponseMessage.

2017-03-07 03:15 UTC, Skaty commented
@samsontmr Not really possible if the methods are not exported.

2017-03-07 03:17 UTC, samsontmr commented
Hm how would you normally test index.js files then?

2017-03-07 03:19 UTC, li-kai commented
You'd have to export them for testing. No other way out, unfortunately.

2017-03-07 03:21 UTC, samsontmr commented
Oh...

2017-03-07 04:10 UTC, Skaty commented
@samsontmr You can define the functions and then export them.

Example:
```javascript
function a() {

}

function b() {
  // uses function a
}

module.exports = { 
  a: a,
  b: b
};
```

2017-03-07 04:11 UTC, samsontmr commented
@Skaty great we can do that for those methods that need testing then.

2017-03-07 04:12 UTC, Skaty commented
@samsontmr Should I create a new PR to move those files? That way, at least this PR is purely about tests.

2017-03-07 04:15 UTC, samsontmr commented
@Skaty oh what I meant was you can create the export for the methods in index.js. I want to have some tests in place before moving the methods out into a separate class.

2017-03-07 12:46 UTC, li-kai approved these changes
Just one change, everything else looks good.

2017-03-07 12:46 UTC, li-kai commented on spec/index_spec.js
> +    afterEach(function() {
Since you are resetting the env variables on `beforeEach`, I think this is redundant.

2017-03-07 13:25 UTC, Skaty commented on spec/index_spec.js
> +    afterEach(function() {
Oh, yeah.

2017-03-07 14:05 UTC, merged